[package]
name = "cnctd_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
async-openai = "0.29.3"
reqwest = "0.12.23"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
